// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/application.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/application.go --destination=mock/application.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "main/internal/domain/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPassManager is a mock of IPassManager interface.
type MockIPassManager struct {
	ctrl     *gomock.Controller
	recorder *MockIPassManagerMockRecorder
	isgomock struct{}
}

// MockIPassManagerMockRecorder is the mock recorder for MockIPassManager.
type MockIPassManagerMockRecorder struct {
	mock *MockIPassManager
}

// NewMockIPassManager creates a new mock instance.
func NewMockIPassManager(ctrl *gomock.Controller) *MockIPassManager {
	mock := &MockIPassManager{ctrl: ctrl}
	mock.recorder = &MockIPassManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPassManager) EXPECT() *MockIPassManagerMockRecorder {
	return m.recorder
}

// BuildPassSlots mocks base method.
func (m *MockIPassManager) BuildPassSlots(bookings []models.Booking, totalSlots int) []models.PassSlot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPassSlots", bookings, totalSlots)
	ret0, _ := ret[0].([]models.PassSlot)
	return ret0
}

// BuildPassSlots indicates an expected call of BuildPassSlots.
func (mr *MockIPassManagerMockRecorder) BuildPassSlots(bookings, totalSlots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPassSlots", reflect.TypeOf((*MockIPassManager)(nil).BuildPassSlots), bookings, totalSlots)
}

// MockILocationResolver is a mock of ILocationResolver interface.
type MockILocationResolver struct {
	ctrl     *gomock.Controller
	recorder *MockILocationResolverMockRecorder
	isgomock struct{}
}

// MockILocationResolverMockRecorder is the mock recorder for MockILocationResolver.
type MockILocationResolverMockRecorder struct {
	mock *MockILocationResolver
}

// NewMockILocationResolver creates a new mock instance.
func NewMockILocationResolver(ctrl *gomock.Controller) *MockILocationResolver {
	mock := &MockILocationResolver{ctrl: ctrl}
	mock.recorder = &MockILocationResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILocationResolver) EXPECT() *MockILocationResolverMockRecorder {
	return m.recorder
}

// GetLink mocks base method.
func (m *MockILocationResolver) GetLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockILocationResolverMockRecorder) GetLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockILocationResolver)(nil).GetLink), name)
}
