// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/http/html/errs/errs.go
//
// Generated by this command:
//
//	mockgen --source=internal/interfaces/http/html/errs/errs.go --destination=mock/html_errs.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockIErrorHandler is a mock of IErrorHandler interface.
type MockIErrorHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIErrorHandlerMockRecorder
	isgomock struct{}
}

// MockIErrorHandlerMockRecorder is the mock recorder for MockIErrorHandler.
type MockIErrorHandlerMockRecorder struct {
	mock *MockIErrorHandler
}

// NewMockIErrorHandler creates a new mock instance.
func NewMockIErrorHandler(ctrl *gomock.Controller) *MockIErrorHandler {
	mock := &MockIErrorHandler{ctrl: ctrl}
	mock.recorder = &MockIErrorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIErrorHandler) EXPECT() *MockIErrorHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockIErrorHandler) Handle(ctx *gin.Context, tmplName string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", ctx, tmplName, err)
}

// Handle indicates an expected call of Handle.
func (mr *MockIErrorHandlerMockRecorder) Handle(ctx, tmplName, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockIErrorHandler)(nil).Handle), ctx, tmplName, err)
}
