// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/location/contract.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/location/contract.go --destination=mock/location_link_provider.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockILinkProvider is a mock of ILinkProvider interface.
type MockILinkProvider struct {
	ctrl     *gomock.Controller
	recorder *MockILinkProviderMockRecorder
	isgomock struct{}
}

// MockILinkProviderMockRecorder is the mock recorder for MockILinkProvider.
type MockILinkProviderMockRecorder struct {
	mock *MockILinkProvider
}

// NewMockILinkProvider creates a new mock instance.
func NewMockILinkProvider(ctrl *gomock.Controller) *MockILinkProvider {
	mock := &MockILinkProvider{ctrl: ctrl}
	mock.recorder = &MockILinkProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILinkProvider) EXPECT() *MockILinkProviderMockRecorder {
	return m.recorder
}

// GetLink mocks base method.
func (m *MockILinkProvider) GetLink(location string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", location)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockILinkProviderMockRecorder) GetLink(location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockILinkProvider)(nil).GetLink), location)
}
