// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/notifier/notifier.go
//
// Generated by this command:
//
//	mockgen --source=internal/domain/notifier/notifier.go --destination=mock/notifier.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "main/internal/domain/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockINotifier is a mock of INotifier interface.
type MockINotifier struct {
	ctrl     *gomock.Controller
	recorder *MockINotifierMockRecorder
	isgomock struct{}
}

// MockINotifierMockRecorder is the mock recorder for MockINotifier.
type MockINotifierMockRecorder struct {
	mock *MockINotifier
}

// NewMockINotifier creates a new mock instance.
func NewMockINotifier(ctrl *gomock.Controller) *MockINotifier {
	mock := &MockINotifier{ctrl: ctrl}
	mock.recorder = &MockINotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotifier) EXPECT() *MockINotifierMockRecorder {
	return m.recorder
}

// NotifyBookingCancellation mocks base method.
func (m *MockINotifier) NotifyBookingCancellation(params models.NotifierParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyBookingCancellation", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyBookingCancellation indicates an expected call of NotifyBookingCancellation.
func (mr *MockINotifierMockRecorder) NotifyBookingCancellation(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyBookingCancellation", reflect.TypeOf((*MockINotifier)(nil).NotifyBookingCancellation), params)
}

// NotifyBookingConfirmation mocks base method.
func (m *MockINotifier) NotifyBookingConfirmation(params models.NotifierParams, cancellationLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyBookingConfirmation", params, cancellationLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyBookingConfirmation indicates an expected call of NotifyBookingConfirmation.
func (mr *MockINotifierMockRecorder) NotifyBookingConfirmation(params, cancellationLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyBookingConfirmation", reflect.TypeOf((*MockINotifier)(nil).NotifyBookingConfirmation), params, cancellationLink)
}

// NotifyBookingReminder mocks base method.
func (m *MockINotifier) NotifyBookingReminder(params models.NotifierParams, cancellationLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyBookingReminder", params, cancellationLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyBookingReminder indicates an expected call of NotifyBookingReminder.
func (mr *MockINotifierMockRecorder) NotifyBookingReminder(params, cancellationLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyBookingReminder", reflect.TypeOf((*MockINotifier)(nil).NotifyBookingReminder), params, cancellationLink)
}

// NotifyClassCancellation mocks base method.
func (m *MockINotifier) NotifyClassCancellation(params models.NotifierParams, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClassCancellation", params, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClassCancellation indicates an expected call of NotifyClassCancellation.
func (mr *MockINotifierMockRecorder) NotifyClassCancellation(params, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClassCancellation", reflect.TypeOf((*MockINotifier)(nil).NotifyClassCancellation), params, msg)
}

// NotifyClassUpdate mocks base method.
func (m *MockINotifier) NotifyClassUpdate(params models.NotifierParams, msg, cancellationLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyClassUpdate", params, msg, cancellationLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyClassUpdate indicates an expected call of NotifyClassUpdate.
func (mr *MockINotifierMockRecorder) NotifyClassUpdate(params, msg, cancellationLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClassUpdate", reflect.TypeOf((*MockINotifier)(nil).NotifyClassUpdate), params, msg, cancellationLink)
}

// NotifyConfirmationLink mocks base method.
func (m *MockINotifier) NotifyConfirmationLink(email, firstName, confirmationLink string, classStartTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyConfirmationLink", email, firstName, confirmationLink, classStartTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyConfirmationLink indicates an expected call of NotifyConfirmationLink.
func (mr *MockINotifierMockRecorder) NotifyConfirmationLink(email, firstName, confirmationLink, classStartTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyConfirmationLink", reflect.TypeOf((*MockINotifier)(nil).NotifyConfirmationLink), email, firstName, confirmationLink, classStartTime)
}

// NotifyPassActivation mocks base method.
func (m *MockINotifier) NotifyPassActivation(email string, passSlots []models.PassSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPassActivation", email, passSlots)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPassActivation indicates an expected call of NotifyPassActivation.
func (mr *MockINotifierMockRecorder) NotifyPassActivation(email, passSlots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPassActivation", reflect.TypeOf((*MockINotifier)(nil).NotifyPassActivation), email, passSlots)
}
