// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/repositories.go
//
// Generated by this command:
//
//	mockgen --source=internal/domain/repositories/repositories.go --destination=mock/repositories.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "main/internal/domain/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIClasses is a mock of IClasses interface.
type MockIClasses struct {
	ctrl     *gomock.Controller
	recorder *MockIClassesMockRecorder
	isgomock struct{}
}

// MockIClassesMockRecorder is the mock recorder for MockIClasses.
type MockIClassesMockRecorder struct {
	mock *MockIClasses
}

// NewMockIClasses creates a new mock instance.
func NewMockIClasses(ctrl *gomock.Controller) *MockIClasses {
	mock := &MockIClasses{ctrl: ctrl}
	mock.recorder = &MockIClassesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClasses) EXPECT() *MockIClassesMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIClasses) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIClassesMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIClasses)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIClasses) Get(ctx context.Context, id uuid.UUID) (models.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(models.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIClassesMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIClasses)(nil).Get), ctx, id)
}

// Insert mocks base method.
func (m *MockIClasses) Insert(ctx context.Context, classes []models.Class) ([]models.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, classes)
	ret0, _ := ret[0].([]models.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIClassesMockRecorder) Insert(ctx, classes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIClasses)(nil).Insert), ctx, classes)
}

// List mocks base method.
func (m *MockIClasses) List(ctx context.Context) ([]models.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIClassesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIClasses)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockIClasses) Update(ctx context.Context, id uuid.UUID, update map[string]any) (models.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, update)
	ret0, _ := ret[0].(models.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIClassesMockRecorder) Update(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIClasses)(nil).Update), ctx, id, update)
}

// MockIBookings is a mock of IBookings interface.
type MockIBookings struct {
	ctrl     *gomock.Controller
	recorder *MockIBookingsMockRecorder
	isgomock struct{}
}

// MockIBookingsMockRecorder is the mock recorder for MockIBookings.
type MockIBookingsMockRecorder struct {
	mock *MockIBookings
}

// NewMockIBookings creates a new mock instance.
func NewMockIBookings(ctrl *gomock.Controller) *MockIBookings {
	mock := &MockIBookings{ctrl: ctrl}
	mock.recorder = &MockIBookingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBookings) EXPECT() *MockIBookingsMockRecorder {
	return m.recorder
}

// CountForClassID mocks base method.
func (m *MockIBookings) CountForClassID(ctx context.Context, classID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForClassID", ctx, classID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForClassID indicates an expected call of CountForClassID.
func (mr *MockIBookingsMockRecorder) CountForClassID(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForClassID", reflect.TypeOf((*MockIBookings)(nil).CountForClassID), ctx, classID)
}

// CountForPassID mocks base method.
func (m *MockIBookings) CountForPassID(ctx context.Context, passID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForPassID", ctx, passID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForPassID indicates an expected call of CountForPassID.
func (mr *MockIBookingsMockRecorder) CountForPassID(ctx, passID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForPassID", reflect.TypeOf((*MockIBookings)(nil).CountForPassID), ctx, passID)
}

// Delete mocks base method.
func (m *MockIBookings) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIBookingsMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIBookings)(nil).Delete), ctx, id)
}

// GetByEmailAndClassID mocks base method.
func (m *MockIBookings) GetByEmailAndClassID(ctx context.Context, classID uuid.UUID, email string) (models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailAndClassID", ctx, classID, email)
	ret0, _ := ret[0].(models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailAndClassID indicates an expected call of GetByEmailAndClassID.
func (mr *MockIBookingsMockRecorder) GetByEmailAndClassID(ctx, classID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailAndClassID", reflect.TypeOf((*MockIBookings)(nil).GetByEmailAndClassID), ctx, classID, email)
}

// GetByID mocks base method.
func (m *MockIBookings) GetByID(ctx context.Context, id uuid.UUID) (models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIBookingsMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIBookings)(nil).GetByID), ctx, id)
}

// Insert mocks base method.
func (m *MockIBookings) Insert(ctx context.Context, booking models.Booking) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, booking)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIBookingsMockRecorder) Insert(ctx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIBookings)(nil).Insert), ctx, booking)
}

// List mocks base method.
func (m *MockIBookings) List(ctx context.Context) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIBookingsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIBookings)(nil).List), ctx)
}

// ListByClassID mocks base method.
func (m *MockIBookings) ListByClassID(ctx context.Context, classID uuid.UUID) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClassID", ctx, classID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClassID indicates an expected call of ListByClassID.
func (mr *MockIBookingsMockRecorder) ListByClassID(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClassID", reflect.TypeOf((*MockIBookings)(nil).ListByClassID), ctx, classID)
}

// ListByPassID mocks base method.
func (m *MockIBookings) ListByPassID(ctx context.Context, passID int) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPassID", ctx, passID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPassID indicates an expected call of ListByPassID.
func (mr *MockIBookingsMockRecorder) ListByPassID(ctx, passID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPassID", reflect.TypeOf((*MockIBookings)(nil).ListByPassID), ctx, passID)
}

// ListWithoutPassByEmail mocks base method.
func (m *MockIBookings) ListWithoutPassByEmail(ctx context.Context, email string, limit int) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithoutPassByEmail", ctx, email, limit)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithoutPassByEmail indicates an expected call of ListWithoutPassByEmail.
func (mr *MockIBookingsMockRecorder) ListWithoutPassByEmail(ctx, email, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithoutPassByEmail", reflect.TypeOf((*MockIBookings)(nil).ListWithoutPassByEmail), ctx, email, limit)
}

// Update mocks base method.
func (m *MockIBookings) Update(ctx context.Context, id uuid.UUID, update map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIBookingsMockRecorder) Update(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIBookings)(nil).Update), ctx, id, update)
}

// MockIPendingBookings is a mock of IPendingBookings interface.
type MockIPendingBookings struct {
	ctrl     *gomock.Controller
	recorder *MockIPendingBookingsMockRecorder
	isgomock struct{}
}

// MockIPendingBookingsMockRecorder is the mock recorder for MockIPendingBookings.
type MockIPendingBookingsMockRecorder struct {
	mock *MockIPendingBookings
}

// NewMockIPendingBookings creates a new mock instance.
func NewMockIPendingBookings(ctrl *gomock.Controller) *MockIPendingBookings {
	mock := &MockIPendingBookings{ctrl: ctrl}
	mock.recorder = &MockIPendingBookingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPendingBookings) EXPECT() *MockIPendingBookingsMockRecorder {
	return m.recorder
}

// GetByConfirmationToken mocks base method.
func (m *MockIPendingBookings) GetByConfirmationToken(ctx context.Context, token string) (models.PendingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByConfirmationToken", ctx, token)
	ret0, _ := ret[0].(models.PendingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByConfirmationToken indicates an expected call of GetByConfirmationToken.
func (mr *MockIPendingBookingsMockRecorder) GetByConfirmationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByConfirmationToken", reflect.TypeOf((*MockIPendingBookings)(nil).GetByConfirmationToken), ctx, token)
}

// Insert mocks base method.
func (m *MockIPendingBookings) Insert(ctx context.Context, booking models.PendingBooking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIPendingBookingsMockRecorder) Insert(ctx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIPendingBookings)(nil).Insert), ctx, booking)
}

// List mocks base method.
func (m *MockIPendingBookings) List(ctx context.Context) ([]models.PendingBooking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.PendingBooking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIPendingBookingsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPendingBookings)(nil).List), ctx)
}

// MockIPasses is a mock of IPasses interface.
type MockIPasses struct {
	ctrl     *gomock.Controller
	recorder *MockIPassesMockRecorder
	isgomock struct{}
}

// MockIPassesMockRecorder is the mock recorder for MockIPasses.
type MockIPassesMockRecorder struct {
	mock *MockIPasses
}

// NewMockIPasses creates a new mock instance.
func NewMockIPasses(ctrl *gomock.Controller) *MockIPasses {
	mock := &MockIPasses{ctrl: ctrl}
	mock.recorder = &MockIPassesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasses) EXPECT() *MockIPassesMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockIPasses) Insert(ctx context.Context, email string, totalSlots int) (models.Pass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, email, totalSlots)
	ret0, _ := ret[0].(models.Pass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIPassesMockRecorder) Insert(ctx, email, totalSlots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIPasses)(nil).Insert), ctx, email, totalSlots)
}

// ListByEmail mocks base method.
func (m *MockIPasses) ListByEmail(ctx context.Context, email string, limit int) ([]models.Pass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEmail", ctx, email, limit)
	ret0, _ := ret[0].([]models.Pass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEmail indicates an expected call of ListByEmail.
func (mr *MockIPassesMockRecorder) ListByEmail(ctx, email, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEmail", reflect.TypeOf((*MockIPasses)(nil).ListByEmail), ctx, email, limit)
}

// MockIContacts is a mock of IContacts interface.
type MockIContacts struct {
	ctrl     *gomock.Controller
	recorder *MockIContactsMockRecorder
	isgomock struct{}
}

// MockIContactsMockRecorder is the mock recorder for MockIContacts.
type MockIContactsMockRecorder struct {
	mock *MockIContacts
}

// NewMockIContacts creates a new mock instance.
func NewMockIContacts(ctrl *gomock.Controller) *MockIContacts {
	mock := &MockIContacts{ctrl: ctrl}
	mock.recorder = &MockIContactsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContacts) EXPECT() *MockIContactsMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockIContacts) Insert(ctx context.Context, email, firstName, lastName string) (models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, email, firstName, lastName)
	ret0, _ := ret[0].(models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIContactsMockRecorder) Insert(ctx, email, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIContacts)(nil).Insert), ctx, email, firstName, lastName)
}

// List mocks base method.
func (m *MockIContacts) List(ctx context.Context) ([]models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIContactsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIContacts)(nil).List), ctx)
}
