// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/sender/sender.go
//
// Generated by this command:
//
//	mockgen --source=internal/infrastructure/sender/sender.go --destination=mock/sender.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	sender "main/internal/infrastructure/sender"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIEmailSender is a mock of IEmailSender interface.
type MockIEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockIEmailSenderMockRecorder
	isgomock struct{}
}

// MockIEmailSenderMockRecorder is the mock recorder for MockIEmailSender.
type MockIEmailSenderMockRecorder struct {
	mock *MockIEmailSender
}

// NewMockIEmailSender creates a new mock instance.
func NewMockIEmailSender(ctrl *gomock.Controller) *MockIEmailSender {
	mock := &MockIEmailSender{ctrl: ctrl}
	mock.recorder = &MockIEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmailSender) EXPECT() *MockIEmailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockIEmailSender) Send(messages ...sender.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range messages {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockIEmailSenderMockRecorder) Send(messages ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIEmailSender)(nil).Send), messages...)
}
