// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/unit_of_work.go
//
// Generated by this command:
//
//	mockgen --source=internal/domain/repositories/unit_of_work.go --destination=mock/unit_of_work.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	repositories "main/internal/domain/repositories"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUnitOfWork is a mock of IUnitOfWork interface.
type MockIUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockIUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockIUnitOfWorkMockRecorder is the mock recorder for MockIUnitOfWork.
type MockIUnitOfWorkMockRecorder struct {
	mock *MockIUnitOfWork
}

// NewMockIUnitOfWork creates a new mock instance.
func NewMockIUnitOfWork(ctrl *gomock.Controller) *MockIUnitOfWork {
	mock := &MockIUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockIUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUnitOfWork) EXPECT() *MockIUnitOfWorkMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockIUnitOfWork) WithTransaction(ctx context.Context, fn func(repositories.Repositories) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockIUnitOfWorkMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockIUnitOfWork)(nil).WithTransaction), ctx, fn)
}
