// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/pendingbookings/contract.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/pendingbookings/contract.go --destination=mock/pendingbookings/pendingbookings.go --package=mockpendingbookings
//

// Package mockpendingbookings is a generated GoMock package.
package mockpendingbookings

import (
	context "context"
	models "main/internal/domain/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CreatePendingBooking mocks base method.
func (m *MockIService) CreatePendingBooking(ctx context.Context, params models.PendingBookingParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingBooking", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingBooking indicates an expected call of CreatePendingBooking.
func (mr *MockIServiceMockRecorder) CreatePendingBooking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingBooking", reflect.TypeOf((*MockIService)(nil).CreatePendingBooking), ctx, params)
}

// MockITokenGenerator is a mock of ITokenGenerator interface.
type MockITokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockITokenGeneratorMockRecorder
	isgomock struct{}
}

// MockITokenGeneratorMockRecorder is the mock recorder for MockITokenGenerator.
type MockITokenGeneratorMockRecorder struct {
	mock *MockITokenGenerator
}

// NewMockITokenGenerator creates a new mock instance.
func NewMockITokenGenerator(ctrl *gomock.Controller) *MockITokenGenerator {
	mock := &MockITokenGenerator{ctrl: ctrl}
	mock.recorder = &MockITokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenGenerator) EXPECT() *MockITokenGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockITokenGenerator) Generate(length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockITokenGeneratorMockRecorder) Generate(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockITokenGenerator)(nil).Generate), length)
}
