// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/classes/contract.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/classes/contract.go --destination=mock/classes/classes.go --package=mockclasses
//

// Package mockclasses is a generated GoMock package.
package mockclasses

import (
	context "context"
	classes "main/internal/application/classes"
	models "main/internal/domain/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CreateClasses mocks base method.
func (m *MockIService) CreateClasses(ctx context.Context, arg1 []models.Class) ([]models.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClasses", ctx, arg1)
	ret0, _ := ret[0].([]models.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClasses indicates an expected call of CreateClasses.
func (mr *MockIServiceMockRecorder) CreateClasses(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClasses", reflect.TypeOf((*MockIService)(nil).CreateClasses), ctx, arg1)
}

// DeleteClass mocks base method.
func (m *MockIService) DeleteClass(ctx context.Context, classID uuid.UUID, msg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClass", ctx, classID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClass indicates an expected call of DeleteClass.
func (mr *MockIServiceMockRecorder) DeleteClass(ctx, classID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClass", reflect.TypeOf((*MockIService)(nil).DeleteClass), ctx, classID, msg)
}

// ListClasses mocks base method.
func (m *MockIService) ListClasses(ctx context.Context, onlyUpcomingClasses bool, classesLimit *int) ([]classes.ClassPresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClasses", ctx, onlyUpcomingClasses, classesLimit)
	ret0, _ := ret[0].([]classes.ClassPresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClasses indicates an expected call of ListClasses.
func (mr *MockIServiceMockRecorder) ListClasses(ctx, onlyUpcomingClasses, classesLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClasses", reflect.TypeOf((*MockIService)(nil).ListClasses), ctx, onlyUpcomingClasses, classesLimit)
}

// UpdateClass mocks base method.
func (m *MockIService) UpdateClass(ctx context.Context, id uuid.UUID, update classes.UpdateClassCommand) (classes.ClassData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClass", ctx, id, update)
	ret0, _ := ret[0].(classes.ClassData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClass indicates an expected call of UpdateClass.
func (mr *MockIServiceMockRecorder) UpdateClass(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClass", reflect.TypeOf((*MockIService)(nil).UpdateClass), ctx, id, update)
}
