// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/passes/contract.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/passes/contract.go --destination=mock/passes/passes.go --package=mockpasses
//

// Package mockpasses is a generated GoMock package.
package mockpasses

import (
	context "context"
	passes "main/internal/application/passes"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// ActivatePass mocks base method.
func (m *MockIService) ActivatePass(ctx context.Context, email string, initialAssignedSlots, totalPassSlots int) (passes.PassActivation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivatePass", ctx, email, initialAssignedSlots, totalPassSlots)
	ret0, _ := ret[0].(passes.PassActivation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivatePass indicates an expected call of ActivatePass.
func (mr *MockIServiceMockRecorder) ActivatePass(ctx, email, initialAssignedSlots, totalPassSlots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivatePass", reflect.TypeOf((*MockIService)(nil).ActivatePass), ctx, email, initialAssignedSlots, totalPassSlots)
}
