// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/bookings/contract.go
//
// Generated by this command:
//
//	mockgen --source=internal/application/bookings/contract.go --destination=mock/bookings/bookings.go --package=mockbookings
//

// Package mockbookings is a generated GoMock package.
package mockbookings

import (
	context "context"
	bookings "main/internal/application/bookings"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockIService) CancelBooking(ctx context.Context, id uuid.UUID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, id, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockIServiceMockRecorder) CancelBooking(ctx, id, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockIService)(nil).CancelBooking), ctx, id, token)
}

// CreateBooking mocks base method.
func (m *MockIService) CreateBooking(ctx context.Context, token string) (bookings.BookingCreation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, token)
	ret0, _ := ret[0].(bookings.BookingCreation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockIServiceMockRecorder) CreateBooking(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockIService)(nil).CreateBooking), ctx, token)
}

// DeleteBooking mocks base method.
func (m *MockIService) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockIServiceMockRecorder) DeleteBooking(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockIService)(nil).DeleteBooking), ctx, id)
}

// GetBookingCancellationForm mocks base method.
func (m *MockIService) GetBookingCancellationForm(ctx context.Context, id uuid.UUID, token string) (bookings.BookingCancellationForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCancellationForm", ctx, id, token)
	ret0, _ := ret[0].(bookings.BookingCancellationForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCancellationForm indicates an expected call of GetBookingCancellationForm.
func (mr *MockIServiceMockRecorder) GetBookingCancellationForm(ctx, id, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCancellationForm", reflect.TypeOf((*MockIService)(nil).GetBookingCancellationForm), ctx, id, token)
}
